# Generated by Django 3.1.1 on 2020-12-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateTimeField(default=datetime.datetime.now)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
