# Generated by Django 3.1.1 on 2020-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
