# Generated by Django 3.1.1 on 2020-12-22 10:25

from django.db import migrations, models
import patients.utils


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='otp',
            field=models.CharField(default=patients.utils.generate_otp, max_length=20, unique=True),
        ),
    ]
