# Generated by Django 3.1.1 on 2020-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_virtualqueue_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualqueue',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='virtualqueue',
            name='removed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
