# Generated by Django 3.1.1 on 2021-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_auto_20201219_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
