# Generated by Django 3.1.1 on 2021-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_queue_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='queue',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
