# Generated by Django 3.1.1 on 2021-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_auto_20210121_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
