# Generated by Django 3.1.1 on 2021-01-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_auto_20210122_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='image',
        ),
    ]
