# Generated by Django 3.1.5 on 2021-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_remove_queue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualqueue',
            name='treatment_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
