# Generated by Django 3.1.2 on 2021-01-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_auto_20210126_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='model',
            field=models.FileField(default='models/default.sav', upload_to='models/'),
        ),
    ]
