# Generated by Django 3.1.5 on 2021-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_queue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
