# Generated by Django 3.1.5 on 2021-02-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_queue_max_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='max_limit',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
