# Generated by Django 3.1.5 on 2021-01-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
